name: ItemEdit
version: ${project.version}
main: net.lordofthecraft.itemedit.ItemEdit
api-version: "1.13"
depend: [Tythan]
commands:
  edit:
    command: /<command>
    description: "Edit your items with cool names and descriptions!"
permissions:

  #Command Access
  itemedit.name:
    default: true
    description: Edit names of items.
  itemedit.desc:
    default: true
    description: Edit descriptions of items.
  itemedit.rarity:
    default: op
    description: Set the rarity of an item.
  itemedit.quality:
    default: op
    description: Set the quality of an item.
  itemedit.aura:
    default: op
    description: Set the aura of an item.
  itemedit.type:
    default: op
    description: Set the type of an item.
  itemedit.approve:
    default: true
    description: Approve items so they can no longer be edited.
  itemedit.placeable:
    default: true
    description: Makes an item incapable of being placed.

  #Staff and base permissions.
  #Add itemedit.PERM.use to approve with the signature, and itemedit.PERM.edit to be able to edit over it.
  itemedit.plugin:
    default: op
    description: Plugin Signature.
    children:
      itemedit.admin: true
  itemedit.admin:
      default: op
      description: Allows access to config settings and provides the admin signature.
      children:
        itemedit.tech: true
  itemedit.tech:
      default: op
      description: Tech Signature
      children:
        itemedit.mod: true
  itemedit.mod:
    default: op
    description: Allows staff to override signatures and provides the mod signature.
  itemedit.lore:
    default: op
    description: Lore Signature
    children:
      itemedit.free: true
  itemedit.event:
    default: op
    description: Event Signature
    children:
      itemedit.st: true
  itemedit.build:
    default: op
    description: Builder Signature
  itemedit.design:
    default: op
    description: Design Signature
  itemedit.use:
    default: true
    description: Base Roleplay and Player signature
    children:
      itemedit.name: true
      itemedit.desc: true
      itemedit.approve: true
      itemedit.potion: true
      itemedit.use.use: true

  #Custom values per person/group.
  itemedit.length:
    default: false
    description: The maximum amount of lines worth of description allowed. Build as itemedit.length.#