name: ItemEdit
version: 1.14.4-R0.1
main: net.lordofthecraft.itemedit.ItemEdit
api-version: "1.13"
depend: [Tythan]
softdepend: [ArcheCore, Foundation, Obelisk]
commands:
  edit:
    command: /<command>
    description: "Edit your items with cool names and descriptions!"
permissions:

  #Base Permission
  itemedit:

    #Command Access
    check:
      default: true
      description: Check to see one's edit tokens.
    prices:
      default: op
      description: Check prices for edit tokens if enabled.
    name:
      default: true
      description: Edit names of items.
    color:
      default: true
      description: Change the color of an item's name.
    desc:
      default: true
      description: Edit descriptions of items.
    glow:
      default: op
      description: Add a glow to items.
    sign:
      default: true
      description: Sign items so they can no longer be edited.
    clear:
      default: true
      description: Clears everything from an item so you can start over.

    #Staff and base permissions.
    admin:
      default: op
      description: Allows access to config settings and provides tha dmin signature.
      children:
        itemedit.mod: true
    dev:
      default: op
      description: Dev Signature
    mod:
      default: op
      description: Allows staff to override signatures and provides the mod signature.
      children:
        itemedit.prices: true
        itemedit.glow: true
    st:
      default: op
      description: Story Signature
    world:
      default: op
      description: World Signature
    comm:
      default: op
      description: Community Signature
    use:
      default: true
      description: Base Roleplay and Player signature
      children:
        itemedit.name: true
        itemedit.color: true
        itemedit.desc: true
        itemedit.sign: true
        itemedit.clear: true
        itemedit.check: true

    #Custom values per person/group.
    length:
      default: false
      description: The maximum amount of lines worth of description allowed. Build as itemedit.length.#
    vip:
      default: false
      description: The amount of VIP tokens one has access to. Build as itemedit.vip.#
    unlimited:
      default: op
      description: Gives maximum VIP edits per week and unlimited description length.